# Generated by Django 3.2 on 2021-05-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('default', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=0)),
                ('tag', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='ShopCollect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('shopname', models.CharField(max_length=255)),
                ('add_time', models.DateField()),
            ],
            options={
                'db_table': 'shop_collect',
            },
        ),
        migrations.CreateModel(
            name='UserEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('wallet', models.IntegerField(default=0)),
                ('gender', models.CharField(max_length=10)),
                ('user_img', models.CharField(max_length=500)),
                ('status', models.IntegerField(default=0)),
                ('add_time', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
