# Generated by Django 3.2 on 2021-05-05 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('shop_id', models.IntegerField()),
                ('pay_money', models.IntegerField()),
                ('box_cost', models.IntegerField()),
                ('send_cost', models.IntegerField()),
                ('address', models.CharField(max_length=500)),
                ('note', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=255)),
                ('user_mobile', models.CharField(max_length=255)),
                ('shopname', models.CharField(max_length=255)),
                ('shop_mobile', models.CharField(max_length=255)),
                ('deliver_name', models.CharField(max_length=255)),
                ('deliver_mobile', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('add_time', models.DateField()),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=0)),
                ('add_time', models.DateField()),
            ],
            options={
                'db_table': 'shop',
            },
        ),
        migrations.CreateModel(
            name='ShopInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_man', models.CharField(max_length=255)),
                ('contact_mobile', models.CharField(max_length=255)),
                ('cateid', models.IntegerField(default=0)),
                ('begin_time', models.DateField(auto_now=True)),
                ('end_time', models.DateField(auto_now=True)),
                ('store_img', models.CharField(max_length=500)),
                ('instore_img', models.CharField(max_length=500)),
                ('logo_img', models.CharField(max_length=500)),
                ('idCard_img', models.CharField(max_length=500)),
                ('business_img', models.CharField(max_length=500)),
                ('license_img', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=255)),
                ('score', models.IntegerField(default=0)),
                ('box', models.IntegerField(default=0)),
                ('floor_send_cost', models.IntegerField(default=0)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderapp.shop', verbose_name='商铺')),
            ],
            options={
                'db_table': 'shop_info',
            },
        ),
        migrations.CreateModel(
            name='OrderFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('shop_id', models.IntegerField()),
                ('food_id', models.IntegerField()),
                ('shopname', models.CharField(max_length=255)),
                ('food_name', models.CharField(max_length=255)),
                ('cover_img', models.CharField(max_length=500)),
                ('sell_price', models.IntegerField()),
                ('tag', models.CharField(max_length=255)),
                ('note', models.CharField(max_length=500)),
                ('add_time', models.DateField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderapp.order', verbose_name='订单表')),
            ],
            options={
                'db_table': 'order_food',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=255)),
                ('note', models.CharField(max_length=500)),
                ('cover_img', models.CharField(max_length=500)),
                ('sell_price', models.IntegerField()),
                ('total_sales', models.IntegerField()),
                ('month_sales', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('add_time', models.DateField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderapp.shop', verbose_name='商铺')),
            ],
            options={
                'db_table': 'food',
            },
        ),
    ]
